//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD_BussinessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public Compra()
        {
            this.DetalheCompras = new HashSet<DetalheCompra>();
        }
    
        public int IdCompra { get; set; }
        public System.DateTime DtCompra { get; set; }
    
        public virtual ICollection<DetalheCompra> DetalheCompras { get; set; }
        public virtual Comprador Comprador { get; set; }
    }
}
