//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD_BussinessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprador
    {
        public Comprador()
        {
            this.Compras = new HashSet<Compras>();
        }
    
        public int IdCoprador { get; set; }
        public string NomeComprador { get; set; }
    
        public virtual ICollection<Compras> Compras { get; set; }
    }
}
