//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD_BussinessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public Compras()
        {
            this.DetalheCompras = new HashSet<DetalheCompras>();
        }
    
        public int IdCompra { get; set; }
    
        public virtual ICollection<DetalheCompras> DetalheCompras { get; set; }
    }
}
