//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD_BussinessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalheCompra
    {
        public int IdDetalheCompra { get; set; }
        public int ComprasIdCompra { get; set; }
        public int QtdeProdutoCompra { get; set; }
        public int ProdutoIdProduto { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
