//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD_BussinessEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int IdProduto { get; set; }
        public string DescricaoProduto { get; set; }
        public int FornecedorIdFornecedor { get; set; }
        public int DetalheComprasIdDetalheCompra { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual DetalheCompras DetalheCompras { get; set; }
    }
}
